name: Generate README cards

on:
  schedule:
    - cron: "0 0 * * *" # Runs once daily at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&rank_icon=github
          path: dist/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate stats dark card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&rank_icon=github&theme=dark
          path: dist/stats-dark.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate top languages card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&layout=compact
          path: dist/top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate top languages dark card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&layout=compact&theme=dark
          path: dist/top-langs-dark.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate snake card
        uses: Platane/snk@v3
        with:
          # github user name to read the contribution graph from (**required**)
          # using action context var `github.repository_owner` or specified user
          github_user_name: ${{ github.repository_owner }}
      
          # list of files to generate.
          # one file per line. Each output can be customized with options as query string.
          #
          #  supported options:
          #  - palette:           A preset of color, one of [github, github-dark, github-light]
          #  - color_snake:       Color of the snake
          #  - color_dots:        Coma separated list of dots color.
          #                       The first one is 0 contribution, then it goes from the low contribution to the highest.
          #                       Exactly 5 colors are expected.
          #  - color_background:  Color of the background (for gif only)
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9&color_background=#aaaaaa

      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add dist/*.svg
          git commit -m "Update README cards" || exit 0
          git push

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 30
          keep_minimum_runs: 6
